const COURSES_DATA = {
    "Mathématiques": [
        { "title": "Suites Numériques", "title_ar": "المتتاليات العددية", "desc": "Calcul de limites, convergence et récurrence.", "desc_ar": "حساب النهايات، التقارب والترجع.", "url": "https://www.alloschool.com/course/mathematiques-2eme-bac-sciences-physiques-biof/suites-numeriques-cours" },
        { "title": "Continuité et Limites", "title_ar": "الاتصال والنهايات", "desc": "Théorème des valeurs intermédiaires, limites usuelles.", "desc_ar": "مبرهنة القيم الوسيطية، النهايات الاعتيادية.", "url": "https://www.alloschool.com/course/mathematiques-2eme-bac-sciences-physiques-biof/continuite-d-une-fonction-numerique-cours" },
        { "title": "Dérivation et Étude de Fonctions", "title_ar": "الاشتقاق ودراسة الدوال", "desc": "Tableau de variations, branches infinies, concavité.", "desc_ar": "جدول التغيرات، الفروع اللانهائية، التقعر.", "url": "https://www.alloschool.com/course/mathematiques-2eme-bac-sciences-physiques-biof/derivation-et-etude-des-fonctions-cours" },
        { "title": "Fonctions Logarithmiques", "title_ar": "الدوال اللوغاريتمية", "desc": "Propriétés de ln, limites et dérivées.", "desc_ar": "خاصيات ln، النهايات والاشتقاق.", "url": "https://www.alloschool.com/course/mathematiques-2eme-bac-sciences-physiques-biof/fonctions-logarithmes-cours" },
        { "title": "Fonctions Exponentielles", "title_ar": "الدوال الأسية", "desc": "La fonction exp, équations et inéquations.", "desc_ar": "الدالة الأسية، المعادلات والمتراجحات.", "url": "https://www.alloschool.com/course/mathematiques-2eme-bac-sciences-physiques-biof/fonctions-exponentielles-cours" },
        { "title": "Nombres Complexes", "title_ar": "الأعداد العقدية", "desc": "Forme algébrique, trigonométrique et exponentielle.", "desc_ar": "الشكل الجبري، المثلثي والأسسي.", "url": "https://www.alloschool.com/course/mathematiques-2eme-bac-sciences-physiques-biof/nombres-complexes-partie-1-cours" },
        { "title": "Calcul Intégral", "title_ar": "الحساب التكاملي", "desc": "Primitives, intégration par parties, calcul d'aires.", "desc_ar": "الدوال الأصلية، التكامل بالأجزاء، حساب المساحات.", "url": "https://www.alloschool.com/course/mathematiques-2eme-bac-sciences-physiques-biof/calcul-integral-cours" },
        { "title": "Équations Différentielles", "title_ar": "المعادلات التفاضلية", "desc": "Résolution des types y' = ay + b.", "desc_ar": "حل المعادلات من نوع y' = ay + b.", "url": "https://www.alloschool.com/course/mathematiques-2eme-bac-sciences-physiques-biof/equations-differentielles-cours" },
        { "title": "Géométrie dans l'espace", "title_ar": "الهندسة في الفضاء", "desc": "Produit scalaire, produit vectoriel, plans.", "desc_ar": "الجداء السلمي، الجداء المتجهي، المستويات.", "url": "https://www.alloschool.com/course/mathematiques-2eme-bac-sciences-physiques-biof/geometrie-dans-l-espace-cours" },
        { "title": "Probabilités", "title_ar": "الاحتمالات", "desc": "Dénombrement, variables aléatoires, loi binomiale.", "desc_ar": "التعداد، المتغيرات العشوائية، القانون الحداني.", "url": "https://www.alloschool.com/course/mathematiques-2eme-bac-sciences-physiques-biof/probabilites-cours" }
    ],
    "Physique-Chimie": [
        { "title": "Ondes Mécaniques", "title_ar": "الموجات الميكانيكية", "desc": "Propagation, ondes progressives périodiques.", "desc_ar": "الانتشار، الموجات المتوالية الدورية.", "url": "https://www.alloschool.com/course/physique-chimie-2eme-bac-sciences-physiques-biof/ondes-mecaniques-progressives-cours" },
        { "title": "Ondes Lumineuses", "title_ar": "الموجات الضوئية", "desc": "Diffraction et dispersion de la lumière.", "desc_ar": "حيود وتبدد الضوء.", "url": "https://www.alloschool.com/course/physique-chimie-2eme-bac-sciences-physiques-biof/ondes-lumineuses-cours" },
        { "title": "Décroissance Radioactive", "title_ar": "التناقص الإشعاعي", "desc": "Noyau, masse et énergie nucléaire.", "desc_ar": "النواة، الكتلة والطاقة النووية.", "url": "https://www.alloschool.com/course/physique-chimie-2eme-bac-sciences-physiques-biof/transformations-nucleaires-decroissance-radioactive-cours" },
        { "title": "Électricité (RC/RL/RLC)", "title_ar": "الكهرباء (RC/RL/RLC)", "desc": "Oscillations libres dans un circuit RLC série.", "desc_ar": "التذبذبات الحرة في دارة RLC متوالية.", "url": "https://www.alloschool.com/course/physique-chimie-2eme-bac-sciences-physiques-biof/electricite-dipole-rc-cours" },
        { "title": "Mécanique (Lois de Newton)", "title_ar": "الميكانيك (قوانين نيوتن)", "desc": "Chute verticale, plans inclinés, satellites.", "desc_ar": "السقوط الرأسي، المستويات المائلة، الأقمار الاصطناعية.", "url": "https://www.alloschool.com/course/physique-chimie-2eme-bac-sciences-physiques-biof/mecanique-lois-de-newton-cours" },
        { "title": "Chimie: Acides et Bases", "title_ar": "الكيمياء: الأحماض والقواعد", "desc": "pH, constante d'équilibre, dosage.", "desc_ar": "pH، ثابتة التوازن، المعايرة.", "url": "https://www.alloschool.com/course/physique-chimie-2eme-bac-sciences-physiques-biof/chimie-transformations-associees-a-des-reactions-acido-basiques-cours" }
    ],
    "SVT": [
        { "title": "Consommation de la Matière Organique", "title_ar": "استهلاك المادة العضوية", "desc": "ATP, Respiration cellulaire et Fermentation.", "desc_ar": "ATP، التنفس الخلوي والتخمر.", "url": "https://www.alloschool.com/course/svt-2eme-bac-sciences-physiques-biof/consommation-de-la-matiere-organique-et-flux-d-energie-cours" },
        { "title": "Nature de l'Information Génétique", "title_ar": "طبيعة الخبر الوراثي", "desc": "ADN, mitose et méiose.", "desc_ar": "ADN، الانقسام غير المباشر والاختزالي.", "url": "https://www.alloschool.com/course/svt-2eme-bac-sciences-physiques-biof/nature-de-l-information-genetique-et-mecanisme-de-son-expression-cours" },
        { "title": "Génétique Humaine", "title_ar": "الوراثة البشرية", "desc": "Arbres généalogiques et maladies héréditaires.", "desc_ar": "شجرات النسب والأمراض الوراثية.", "url": "https://www.alloschool.com/course/svt-2eme-bac-sciences-physiques-biof/la-genetique-humaine-cours" },
        { "title": "Immunologie", "title_ar": "علم المناعة", "desc": "Soi et non-soi, réponse humorale et cellulaire.", "desc_ar": "الذاتي وغير الذاتي، الاستجابة الخلطية والخلوية.", "url": "https://www.alloschool.com/course/svt-2eme-bac-sciences-physiques-biof/l-immunologie-cours" }
    ]
};
